import { existsSync, mkdtempSync, readFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { describe,expect,it } from 'vitest';
import { executeLocalBusinessSpaceIngest, rollbackLocalBusinessSpace } from '../src/services/km/local-business-space-adapter.js';
import type { KmIngestRunReport,KmIngestTargetRecord } from '../src/services/km/observation-store.js';
const target:KmIngestTargetRecord={targetId:'local-space',state:'ready',targetHash:'sha256:t',credentialRef:'mock:local-space',createdBy:'owner',createdAt:'x',updatedAt:'x',target:{endpointRef:'space:database-platform',dryRunOnly:false,allowedProviderIds:[],transport:'local-space',allowedHosts:[],timeoutMs:10000,allowPrivateNetwork:false}};
function report(hash='sha256:c'):KmIngestRunReport{return{run:{runId:'r1',idempotencyKey:'i',state:'approved',targetId:'local-space',plan:{schemaVersion:1,targetId:'local-space',targetHash:'sha256:t',sourceRunId:'e1',extractorRunState:'completed',extractorProviderId:'rules',mode:'offline',dryRun:true,planCalls:{markIngested:false},canonicalKeys:['key']},planHash:'sha256:p',canonicalKeySetHash:'sha256:k',confirmationTokenHash:'sha256:x',externalAck:{approved:true,approvedBy:'owner',planHash:'sha256:p'},sourceCount:1,eligibleCount:1,ingestedCount:0,dedupedCount:0,skippedCount:0,failedCount:0,rollbackCount:0,markIngestedPlannedCount:0,createdBy:'owner',createdAt:'x',updatedAt:'x'},items:[{ingestItemId:'it',runId:'r1',canonicalKey:'key',candidateHash:hash,state:'pending',createdAt:'x',updatedAt:'x',candidate:{targetLayer:'L2',category:'runbook',title:'Title',claimKey:'claim',claimText:'body',confidence:'observed',freshness:'fresh',privacyClass:'internal',sourceRefs:[{kind:'job',ref:'e1'}]}}],audit:[]}}
describe('local business space adapter',()=>{
 it('atomically writes canonical entries and can rollback',()=>{const dir=mkdtempSync(join(tmpdir(),'local-space-'));const ack=executeLocalBusinessSpaceIngest({dataDir:dir,target,report:report(),actorId:'owner'});expect(ack.spaceId).toBe('database-platform');const index=JSON.parse(readFileSync(join(dir,'km-business-spaces/database-platform/INDEX.json'),'utf8'));expect(index.entries.key.contentHash).toBe('sha256:c');expect(existsSync(join(dir,'km-business-spaces/database-platform',index.entries.key.file))).toBe(true);rollbackLocalBusinessSpace({dataDir:dir,spaceId:ack.spaceId,backupId:ack.backupId});expect(existsSync(join(dir,'km-business-spaces/database-platform/INDEX.json'))).toBe(false)});
 it('rejects canonical-key conflicts without overwriting',()=>{const dir=mkdtempSync(join(tmpdir(),'local-space-'));executeLocalBusinessSpaceIngest({dataDir:dir,target,report:report(),actorId:'owner'});expect(()=>executeLocalBusinessSpaceIngest({dataDir:dir,target,report:report('sha256:d'),actorId:'owner'})).toThrow('canonical_conflict')});
 it('rejects path escapes and disabled targets',()=>{const dir=mkdtempSync(join(tmpdir(),'local-space-'));expect(()=>executeLocalBusinessSpaceIngest({dataDir:dir,target:{...target,target:{...target.target,endpointRef:'space:../escape'}},report:report(),actorId:'owner'})).toThrow('space_id_invalid');expect(()=>executeLocalBusinessSpaceIngest({dataDir:dir,target:{...target,state:'disabled'},report:report(),actorId:'owner'})).toThrow('target_not_enabled')});
});
